DhakadGarments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('garments.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

garments/urls.py
from django.conf.urls import url
from . import views

app_name = 'garments'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^billing$', views.billing, name='billing'),
    url(r'^cart$', views.cart, name='cart'),
    url(r'^items$', views.items, name='items'),
    url(r'^items/(?P<is_search>[1])$', views.items, name='items1'),
    url(r'^login_user$', views.login_user, name='login_user'),
    url(r'^logout_user$', views.logout, name='logout_user'),
    url(r'^remove_from_cart/(?P<item_category_id>[0-9]+)$', views.delete_item_category_from_cart, name='remove_from_cart'),
    url(r'^add_to_cart/(?P<item_category_id>[0-9]+)$', views.add_item_category_to_cart, name='add_to_cart'),
    url(r'^place_order/(?P<amount>[0-9\.]+)$', views.place_order, name='place_order'),
    url(r'^admin_home$', views.admin_home, name='admin_home'),
    url(r'^user_profile$', views.user_profile, name='user_profile'),
    url(r'^sign_up$', views.sign_up, name='sign_up'),
    url(r'^sign_up/(?P<is_modify>[0-9]+)$', views.sign_up, name='sign_up'),    
    url(r'^sign_up_page$', views.sign_up_page, name='sign_up_page'),
    url(r'^detail/(?P<item_category_id>[0-9]+)$', views.item_detail, name='item_detail'),
    url(r'^add_feedback/(?P<item_category_id>[0-9]+)$', views.add_feedback, name='add_feedback'),
    url(r'^view_table/(?P<table_name>[0-9]+)$', views.view_table, name='view_table'),
    url(r'^mark_delivered/(?P<order_id>[0-9]+)$', views.mark_delivered, name='mark_delivered'),
    url(r'^order_details/(?P<order_id>[0-9]+)/(?P<return_to>[A-Z]+)$', views.order_details, name='order_details'),
    url(r'^delete_item_page$', views.delete_item_page, name='delete_item_page'),
    url(r'^delete_item/(?P<item_id>[0-9]+)$', views.delete_item, name='delete_item'),
    url(r'^delete_order_page$', views.delete_order_page, name='delete_order_page'),
    url(r'^delete_order/(?P<order_id>[0-9]+)$', views.delete_order, name='delete_order'),
    url(r'^insert_item$', views.insert_item, name='insert_item'),
    url(r'^insert_item_page$', views.insert_item_page, name='insert_item_page'),
    url(r'^modify_item$', views.modify_item, name='modify_item'),
    url(r'^modify_order_page$', views.modify_order_page, name='modify_order_page'),
    url(r'^modify_order$', views.modify_order, name='modify_order'),
    url(r'^women_items$', views.women_items, name='women_items'),
    url(r'^men_items$', views.men_items, name='men_items'),
    url(r'^kids_items$', views.kids_items, name='kids_items'),
    url(r'^user_order$', views.user_order, name='user_order'),
    url(r'^user_profile$', views.user_profile, name='user_profile'),
    url(r'^post_sign_up/(?P<hashed_username>[\s\S]+)$', views.post_sign_up, name='post_sign_up'),
    url(r'^transaction_status$', views.transaction_status, name='transaction_status'),
    url(r'^modify_item_page$', views.modify_item_page, name='modify_item_page'),
    # url(r'^add_to_cart/(?P<item_category_id>[0-9]+)/(?P<quantity>[0-9]+)$', views.add_item_category_to_cart, name='add_to_cart'),
]

garments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

garments/forms.py
from django import forms

# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ['username', 'email', 'address', 'password']
 
# class CustomerForm(forms.ModelForm):
# 	username = forms.CharField(widget=forms.PasswordInput)
#  	password = forms.CharField(widget=forms.PasswordInput)
#  	email = forms.CharField(widget=forms.EmailField)
#  	first_name = forms.CharField(widget=forms.PasswordInput)
# 	last_name = forms.CharField(widget=forms.PasswordInput)
# 	password = forms.CharField(widget=forms.PasswordInput)
# 	address = forms.CharField(widget=forms.PasswordInput)
# 	phone_no = forms.CharField(widget=forms.PasswordInput)
# 	cart_remarks = forms.CharField(widget=forms.PasswordInput)
# 	is_admin = forms.CharField(widget=forms.CharField)

garments/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
# from .forms import CartForm
from django.db import connection,IntegrityError
from datetime import datetime

from django.core.mail import send_mail

from django.core.mail import EmailMessage
from django.template.loader import render_to_string
# from . import messager
from django.contrib.sites.shortcuts import get_current_site
# # from cryptography.fernet import Fernet
# # key='pGWp5lViKbMrOTFesoBU78ie2BZzFDVYRkWTcJJJ1vs='
# # cipher_suite = Fernet(key)
# # cipher_text = cipher_suite.encrypt("A really secret message. Not for prying eyes.")
# # plain_text = cipher_suite.decrypt(cipher_text)

# import hashlib
# # p='vishal'.encode('utf-8')
# salt='9876abcd'.encode('utf-8')
# # var2 =  hashlib.sha256(p+salt).hexdigest()


# Views Utils
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


def write_file(filename,s):
    with open(filename, 'wb') as f:
        f.write(s)

def transaction_status(request):
    pass


# Views Utils --- User
#----------------------------------------------------- Authentication -----------------------------------------------------
def authenticate(username, password, is_admin):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * from Customer where username = '{}' AND password = MD5('{}') AND is_admin = {} AND is_activated='Y';".format(username, password, is_admin))
        result = dictfetchall(cursor)
    if len(result)>0:
        return result[0]
    return None

def login(request, user, is_admin):
    request.session['id'] = user['id']
    request.session['username'] = user['username']
    request.session['first_name'] = user['first_name']
    request.session['last_name'] = user['last_name']
    request.session['email'] = user['email']
    request.session['phone_no'] = user['phone_no']
    request.session['address'] = user['address']
    request.session['password'] = user['password']
    request.session['cart_remarks'] = user['cart_remarks']
    request.session['is_admin'] = user['is_admin']


def is_authenticated(request):
    if request.session.has_key('username'):
        return True
    return False

def is_authenticated_as_admin(request):
    if request.session.has_key('username') and request.session.has_key('is_admin')==True and not(request.session['is_admin']==0):
        return True
    return False

#----------------------------------------------------- Index -----------------------------------------------------


def get_best_deals(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM ItemCategory ORDER BY discount/mrp DESC LIMIT 10;')
        result = dictfetchall(cursor)
    return result

def index(request):
    best_deals = get_best_deals(request)
    if is_authenticated(request):
        first_name = request.session['first_name']
        user_id = request.session['id']
        cart_items = get_cart_items(user_id)
        for item in best_deals:
            if item['photo'] is not None:
                write_file('./garments/static/garments/images/img-{}.jpg'.format(item['id']) ,  item['photo'])
        if is_authenticated_as_admin(request):
            return render(request, 'garments/index.html', {'admin':'True','cart_items':cart_items, 'first_name': first_name, 'best_deals':best_deals})
        else:
            return render(request, 'garments/index.html', {'cart_items':cart_items, 'first_name': first_name, 'best_deals':best_deals})
    else:
        return render(request, 'garments/index.html', {'error':'True', 'best_deals':best_deals})

#----------------------------------------------------- //Index -----------------------------------------------------


def logout(request):
    try:
        del request.session['username']
        del request.session['first_name']
        del request.session['last_name']
        del request.session['email']
        del request.session['address']
        del request.session['password']
        del request.session['cart_remarks']
        del request.session['id']
        del request.session['phone_no']
        del request.session['is_admin']
    except KeyError:
        best_deals = get_best_deals(request)
        return render(request, 'garments/index.html', {'best_deals':best_deals,'error':'True', 'error_message': 'You have already logged Out.' })
    return index(request)# return render(request, 'garments/index.html', {'error':'True' })



# Login View
def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        is_admin = str(request.POST['is_admin'])
        user = authenticate(username=username, password=password, is_admin=is_admin)
        # return HttpResponse("SELECT * from Customer where username = '{}' AND password = MD5('{}') AND is_admin = {} AND is_activated='Y';".format(username, password, is_admin))
        if user is not None:
            login(request, user, is_admin)
            user_id = request.session['id']
            cart_items = get_cart_items(user_id)
            if user['is_admin']==0:
                return render(request, 'garments/index.html',{'cart_items':cart_items, 'first_name':user['first_name']})
            else:
                return render(request, 'garments/index.html',{'admin':'True', 'cart_items':cart_items, 'first_name':user['first_name']})
        else:
            return render(request, 'garments/index.html', {'error':'True','error_message': 'Invalid username or password. Or Please confirm email if you already signed up.' })
    return render(request, 'garments/index.html', {'error':'True', 'error_message': 'Invalid method' })

def sign_up(request, is_modify=None):
    if request.method == "POST":
        username = request.POST["username"]
        email_id = request.POST["email"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        password = request.POST["password1"]
        password_conf = request.POST["password2"]
        address = request.POST["address"]
        phone_no = request.POST["phone_no"]
        is_admin = 0
        if not(password == password_conf):
            return render(request, 'garments/sign_up.html', {'error':'True','error_message': 'password Mismatch' })
        try:
            with connection.cursor() as cursor:
                if is_modify is None:
                    cursor.execute("INSERT INTO Customer (username, email, password, address, first_name, last_name, phone_no, is_admin, is_activated) VALUES ('{}','{}',MD5('{}'),'{}','{}','{}',{},{},'Y');".format(username, email_id, password, address, first_name, last_name, phone_no, is_admin))
                    cursor.execute("SELECT MD5('{}')".format(username))
                    r = cursor.fetchall()
                else:
                    cursor.execute("UPDATE Customer SET username='{}', email='{}', password=MD5('{}'), address='{}', first_name='{}', last_name='{}', phone_no={};".format(username, email, p, address, first_name, last_name, phone_no))
        except IntegrityError:
            return render(request, 'garments/index.html', {'error':'True', 'error_message': 'Username already registered.' })
        current_site = get_current_site(request)
        # message = 'Please confirm your account on Dhakadgarments by this link : {}'.format(current_site.domain+'/'+hashed_username)
        # messager.sendSMS(phone_no,message,'7726029635','dhakad17')
        return render(request, 'garments/index.html',{'error':'True', 'error_message': 'You need to confirm your account through the link sent to you on your email. You won\'t be able to log in otherwise.' })
    return render(request, 'garments/index.html', {'error':'True', 'error_message': 'Invalid method' })

# Sign Up view
def sign_up_page(request):
    if is_authenticated(request):
        first_name = request.session['first_name']
        user_id = request.session['id']
        cart_items = get_cart_items(user_id)
        return render(request, 'garments/sign_up.html', {'cart_items':cart_items, 'first_name':user['first_name'],'error_message': 'you already registered' })
    else:
        return render(request, 'garments/sign_up.html')

def post_sign_up(request, hashed_username=None):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM Customer WHERE MD5(username)='{}';".format(hashed_username))
        r = dictfetchall(cursor)
        if len(r)==0:
            return render(request, 'garments/index.html', {'error':'True', 'error_message': 'Invalid method' })
        else:
            cursor.execute("UPDATE Customer SET is_activated = 'Y' WHERE MD5(username)='{}';".format(hashed_username))
            cursor.execute("SELECT * FROM Customer WHERE MD5(username)='{}';".format(hashed_username))
            user = dictfetchall(cursor)[0]
            login(request, user, 0)
    return render(request, 'garments/index.html', {'error':'True', 'error_message': 'Invalid method' })

#----------------------------------------------------- //Authentication -----------------------------------------------------






#----------------------------------------------------- ADMIN -----------------------------------------------------

def admin_home(request):
    if is_authenticated_as_admin(request):
        first_name = request.session['first_name']
        user_id = request.session['id']
        cart_items = get_cart_items(user_id)

garments/templates/garments/admin_manage_tables.html
{% extends error|yesno:"garments/base_visitor.html,garments/base.html" %}
{% load static %}


{% block title %} Home: DGarments {% endblock %}
{% block SecHeader %} {% endblock %}

{% block style %} 
	#main{
		display: -webkit-flex; /* Safari */
    	-webkit-flex-wrap: wrap; /* Safari 6.1+ */
    	display: flex;
    	flex-wrap: wrap;
    }

    #main div {
	    display: inline-block;
    	width: 200px;
    	height: 350px;
    	margin-top:20px;
    	border: 2px blue;
	}
	.alert {
	    padding: 20px;
	    background-color: #f44336;
	    color: white;
	    opacity: 1;
	    transition: opacity 0.6s;
	    margin-bottom: 15px;
	}

	.closebtn {
	    margin-left: 15px;
	    color: white;
	    font-weight: bold;
	    float: right;
	    font-size: 22px;
	    line-height: 20px;
	    cursor: pointer;
	    transition: 0.3s;
	}

	.closebtn:hover {
	    color: black;
	}
{% endblock %}


<!-- header -->
{% block Name %} {{ first_name }} {% endblock %}

{% block cart_descriptor %}
[
	{% if cart_items %}
		{{ cart_items|length }} 
	{% else %}
		0
	{% endif %}
]
{% endblock %}


{% block nav_options %}
	{% if admin == "True" %}
		<li><a href="{% url 'garments:admin_home' %}" >Administrator</a></li>
	{% endif %}
{% endblock %}
<!-- //header -->







{% block body %} 

<!-- Error Message -->
{% if error_message %}
	<div class="alert">
	  <span class="closebtn">&times;</span>  
	  <strong>Error!</strong> {{ error_message }}
	</div>

	<script>
		var close = document.getElementsByClassName("closebtn");
		var i;

		for (i = 0; i < close.length; i++) {
		    close[i].onclick = function(){
		        var div = this.parentElement;
		        div.style.opacity = "0";
		        setTimeout(function(){ div.style.display = "none"; }, 600);
		    }
		}
	</script>
{% endif %}
<!-- //Error Message -->


<div>
	<div class='row'>
		<div class="col-md-1"> </div>
		<div class="col-md-10">
			<div class="thumbnail"  style='margin-top:1%;margin-bottom:5%;padding:5%;box-shadow: 0 0 1px blue;width:103%;'>
					
			<div style='text-align:center;'>
				<h2 style='color:rgb(0,100,180);'>DATABASE ACCESS</h2>
			</div>

			<div class='row'>
			<div class='col-md-2'></div>
			<div class='col-md-10'>
					<h3> Items</h3><br>
						<a href='{% url "garments:view_table" 1 %}' class='btn btn-primary'>View Items in the Database</a>
					<br>
						<a href='{% url "garments:insert_item_page" %}' class='btn btn-primary'> Add New Items in the Database </a>
					<br>
						<a href='{% url "garments:insert_item_page" %}' class='btn btn-primary'> Modify Existing Items in the Database </a>
					<br>
						<a href='{% url "garments:delete_item_page" %}' class='btn btn-primary'>Delete Items in the Database</a>
					
						</div>
			</div><hr><br>

			<div class='row'>
					<div class='col-md-2'></div>			<div class='col-md-10'>
					<h3> Orders</h3><br>
						<a href='{% url "garments:view_table" 5 %}' class='btn btn-primary'>View Orders and mark them Delivered</a><br>
						<a href='{% url "garments:modify_order_page" %}' class='btn btn-primary'>Modify details of Existing Order</a>
					<br>
						<a href='{% url "garments:delete_order_page" %}' class='btn btn-primary'>Delete an Existing Order</a>
			</div>
			</div><hr><br>

			<div class='row'>
			<div class='col-md-2'></div>			<div class='col-md-10'>
					<h3> Users</h3><br>
					
						<a href='{% url "garments:view_table" 2 %}' class='btn btn-primary' >View</a>
					</div>
			</div><hr><br>

			<div class='row'>
					<div class='col-md-2'></div>			<div class='col-md-10'>
					<h3> Transaction</h3><br>
					
						<a href='{% url "garments:view_table" 3 %}' class='btn btn-primary'>View</a>
				</div>	
			</div><hr><br>
			

		
			</div>
		</div>
	</div>
</div>

{% endblock %}

garments/templates/garments/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %} DhakadGarments {% endblock %}</title>
	{% load staticfiles %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
	<!-- Add icon library -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" type="text/css" href="{% static 'garments/style.css' %}"/>
	{% block head %} {% endblock %}
	<style>
	{% block style %} {% endblock %}
	</style>
</head>

<body>

<!-- header -->
<div class="header" id="home">
	<div class="container">
		<ul>
			<li><i class="fa fa-phone" aria-hidden="true"></i> Call : 7726029635</li>
			<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:dhakad.garments.17@gmail.com">dhakad_garments@gmail.com</a></li>
			<li> <a href="#" data-toggle="modal" data-target="#myModal"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Sign In </a></li>
			<li> <a href="{% url 'garments:sign_up_page' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Sign Up </a></li>
			<!-- <li> <a href="#" data-toggle="modal" data-target="#myModal1"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Sign Up </a></li> -->
		</ul>
	</div>
</div>
<!-- //header -->

<!-- sec-header -->
{% block SecHeader %} {% endblock %}
<!-- //sec-header -->



<nav class="navbar navbar-inverse" style='border:0; margin-bottom: 0;margin-top: 0;'>
  <div class="container-fluid">
	<div class="navbar-header">
	  <a class="navbar-brand" href="#" style="font-size: 20px;" >Dhakad Garments</a>
	</div>
	<ul class="nav navbar-nav" style='color:rgb(255,255,255);'>
	  <li class="active"><a href="{% url 'garments:index' %}" style='background-color: #2fdab8;color:rgb(0,0,0)'>Home</a></li>
	  <li><a href="{% url 'garments:items' %}" >Item Store</a></li>
	  <li><a href="#main" >Offers</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
		<li>
			<a id='cart_btn'  href="{% url 'garments:cart' %}"  type="button" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a>
		</li>
	</ul>
	<form class="navbar-form navbar-left"  action='{% url "garments:items1" 1 %}'  method='post'>
	{% csrf_token %}
	  <div class="input-group">
		<input type="text" name='search_box' class="form-control" placeholder="Search">
		<div class="input-group-btn">
		  <button class="btn btn-default" type="submit">
			<i class="glyphicon glyphicon-search"></i>
		  </button>
		</div>
	  </div>
	</form>
  </div>
</nav> 

{% block body %} {% endblock %}

<!-- footer -->
<div class='jumbotron' style='background-color: rgb(215,215,215);margin: 0;padding: 5%'>
	<div class="footer">
	<h3>Contact Us</h3>
	<div class='container'>
		<div class='col-sm-4' text-align=center><a class='fa fa-facebook' href='#' >&nbsp;&nbsp;facebook</a></div>
		<div class='col-sm-4' text-align=center><a class='fa fa-twitter' href='#' >&nbsp;&nbsp;twitter</a></div>
		<div class='col-sm-4' text-align=center><a class='fa fa-instagram' href='#' >&nbsp;&nbsp;instagram</a></div>
	</div>
</div>


<!-- Modal for Login -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header"  style='background-color: rgb(0,0,0);'>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title">LogIn</h4>
        </div>
        <div class='jumbotron' style='background-color: rgb(255,255,255);margin-bottom: 0;'>
	        <div class="modal-body">
			      <form class="form-horizontal" action="{% url 'garments:login_user' %}" method='post'>
				    {% csrf_token %}
				    <div class="form-group">
				      <label class="control-label col-sm-2" for="username">Username:</label>
				      <div class="col-sm-10">
				        <input type="username" name='username' class="form-control" id="username" placeholder="Enter email">
				      </div>
			  	    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-2" for="pwd">Password:</label>
				      <div class="col-sm-10">
				        <input type="password"  name='password' class="form-control" id="pwd" placeholder="Enter password">
				      </div>
				    </div>
				    <div class="form-group">
				      <div class="col-sm-offset-2 col-sm-10">
				        <div class="checkbox">
				          <label><input type="checkbox"> Remember me</label>
				        </div>
				      </div>
				    </div>
				    <div class="form-group">
				      <div class="col-sm-offset-2 col-sm-10">
				        <div class="checkbox">
	  		        	  <input type="hidden" name="is_admin" value="0" />
				          <label><input type="checkbox" name='is_admin' value="1"> Sign In as Administrator</label>
				        </div>
				      </div>
				    </div>
				    <div class="form-group">
				      <div class="col-sm-offset-2 col-sm-10">
				        <button type="submit" class="btn btn-default">Sign In</button>
				      </div>
				    </div>
				  </form>
	        </div>
	    </div>
        <div class="modal-footer" style='background-color: rgb(255,50,100);margin-top: 0;'>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- //Modal for Login -->




<!-- 
<div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header"  style='background-color: rgb(0,0,0);'>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title">LogIn</h4>
        </div>
        <div class='jumbotron' style='background-color: rgb(255,255,255);margin-bottom: 0;'>
	        <div class="modal-body">
			      <form class="form-horizontal" action="{% url 'garments:sign_up' %}" method='post'>
				    {% csrf_token %}
				    <div class="form-group">
				      <label class="control-label col-sm-2" for="username">Username:</label>
				      <div class="col-sm-10">
				        <input type="username" name='username' class="form-control" id="username" placeholder="Enter email">
				      </div>
			  	    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-2" for="email">Email:</label>
				      <div class="col-sm-10">
				        <input type="email" name='email' class="form-control" id="email" placeholder="Enter Email" required>
				      </div>
			  	    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-2" for="address">Phone No.:</label>
				      <div class="col-sm-10">
				        <input type='tel' name='phone_no' class="form-control" id="phone_no" placeholder="Enter Your Phone No." required>
				      </div>
				    </div>		
				    <div class="form-group">
				      <div class="col-sm-offset-2 col-sm-10">
				        <button type="submit" class="btn btn-default">Sign Up</button>
				      </div>
				    </div>
				  </form>
	        </div>
	    </div>
        <div class="modal-footer" style='background-color: rgb(255,50,100);margin-top: 0;'>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- //Modal for Login --> 

</body>